language: ruby
rvm:
  - 2.4
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake ci
notifications:
  slack: rubyforgood:Z8KxX1B7VPwG7MJFRch66746
services:
  - docker
before_script:
  - chmod -R 0777 spec/fixtures/submission_runners
  - rake docker
